import io
import json
import sqlite3
import pandas as pd
import numpy as np
from datetime import datetime

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm, inch
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, KeepTogether, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from app.services.stats_service import compute_kpis, find_column, forecast_series
from app.core.config import DB_PATH

# Design System Palette
INK = colors.HexColor('#0F172A')
ACCENT_BLUE = colors.HexColor('#2563EB')
POSITIVE = colors.HexColor('#16A34A')
NEGATIVE = colors.HexColor('#DC2626')
MUTED_GRAY = colors.HexColor('#64748B')
LIGHT_ROW_FILL = colors.HexColor('#F1F5F9')
TABLE_HEADER_BG = INK

def format_number(value):
    if value is None or pd.isna(value):
        return "0"
    try:
        val = float(value)
        abs_val = abs(val)
        if abs_val >= 10000000: # 1 Crore
            return f"{val / 10000000:.2f}Cr"
        if abs_val >= 100000: # 1 Lakh
            return f"{val / 100000:.2f}L"
        if abs_val >= 1000: # 1 Thousand
            return f"{val / 1000:.2f}K"
        if val.is_integer():
            return str(int(val))
        return f"{val:.2f}"
    except:
        return str(value)

def matplotlib_formatter(x, pos):
    return format_number(x)

class FooterCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        self.dataset_name = kwargs.pop('dataset_name', '')
        self.gen_date = kwargs.pop('gen_date', '')
        canvas.Canvas.__init__(self, *args, **kwargs)
        self.pages = []

    def showPage(self):
        self.pages.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        page_count = len(self.pages)
        for page in self.pages:
            self.__dict__.update(page)
            self.draw_footer(page_count)
            self.draw_header()
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_footer(self, page_count):
        self.saveState()
        self.setFont('Helvetica', 9)
        self.setFillColor(MUTED_GRAY)
        self.drawString(18*mm, 15*mm, f"Generated by DataMind OS | {self.gen_date}")
        self.drawRightString(A4[0] - 18*mm, 15*mm, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()

    def draw_header(self):
        self.saveState()
        # 4pt accent-blue rule
        self.setFillColor(ACCENT_BLUE)
        self.rect(18*mm, A4[1] - 15*mm, A4[0] - 36*mm, 4, fill=1, stroke=0)
        
        self.setFont('Helvetica-Bold', 8)
        self.setFillColor(INK)
        self.drawString(18*mm, A4[1] - 22*mm, "DATAMIND OS")
        self.setFont('Helvetica', 8)
        self.setFillColor(MUTED_GRAY)
        self.drawRightString(A4[0] - 18*mm, A4[1] - 22*mm, self.dataset_name)
        self.restoreState()

def get_regression_models(dataset_id):
    try:
        conn = sqlite3.connect(str(DB_PATH))
        cursor = conn.cursor()
        cursor.execute('''
            SELECT target, features, r2_test, timestamp
            FROM regression_models
            WHERE dataset_id = ?
            ORDER BY timestamp DESC
        ''', (dataset_id,))
        rows = cursor.fetchall()
        conn.close()
        
        models = []
        for r in rows:
            models.append({
                "target": r[0],
                "features": json.loads(r[1]),
                "r2_test": r[2],
                "timestamp": r[3]
            })
        return models
    except:
        return []
    
def get_outliers(df):
    num_cols = df.select_dtypes(include=[np.number]).columns
    outliers = []
    for col in num_cols:
        clean_col = df[col].dropna()
        if len(clean_col) < 5: continue
        
        mean_val = clean_col.mean()
        std_val = clean_col.std()
        
        if std_val > 0:
            z_scores = ((clean_col - mean_val) / std_val).abs()
            for idx, z in z_scores.items():
                if z > 3:
                    outliers.append({
                        "column": col,
                        "row": str(idx),
                        "value": df.loc[idx, col],
                        "expected": f"µ±3σ ({format_number(mean_val-3*std_val)} to {format_number(mean_val+3*std_val)})",
                        "method": "Z-Score > 3",
                        "z": z
                    })
    
    outliers = sorted(outliers, key=lambda x: x["z"], reverse=True)[:10]
    return outliers

def generate_pdf_report(dataset_info, df):
    buffer = io.BytesIO()
    gen_date = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=18*mm, leftMargin=18*mm,
        topMargin=25*mm, bottomMargin=25*mm
    )
    
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('TitleStyle', fontName='Helvetica-Bold', fontSize=22, textColor=INK, spaceAfter=20, leading=26)
    h2_style = ParagraphStyle('H2Style', fontName='Helvetica-Bold', fontSize=14, textColor=INK, spaceBefore=0, spaceAfter=4, leading=18)
    body_style = ParagraphStyle('BodyStyle', fontName='Helvetica', fontSize=9.5, textColor=INK, spaceAfter=10, leading=13)
    caption_style = ParagraphStyle('CaptionStyle', fontName='Helvetica', fontSize=8, textColor=MUTED_GRAY, spaceBefore=4, spaceAfter=10, leading=11)
    kpi_name_style = ParagraphStyle('KPINameStyle', fontName='Helvetica', fontSize=9.5, textColor=MUTED_GRAY, leading=13)
    kpi_val_style = ParagraphStyle('KPIValStyle', fontName='Helvetica-Bold', fontSize=20, textColor=INK, leading=24)
    kpi_trend_style = ParagraphStyle('KPITrendStyle', fontName='Helvetica', fontSize=9.5, leading=13)
    kpi_source_style = ParagraphStyle('KPISourceStyle', fontName='Courier', fontSize=8, textColor=MUTED_GRAY, leading=11)

    story = []
    
    def section_header(title):
        story.append(Paragraph(title, h2_style))
        # 2pt accent underline bar
        story.append(Table([[""]], colWidths=[doc.width], rowHeights=[2], style=TableStyle([
            ('BACKGROUND', (0,0), (0,0), ACCENT_BLUE),
            ('BOTTOMPADDING', (0,0), (0,0), 0),
            ('TOPPADDING', (0,0), (0,0), 0),
        ])))
        story.append(Spacer(1, 12))

    # ================= PAGE 1 =================
    story.append(Paragraph("Data Analysis Report", title_style))
    
    # 3-stat strip
    date_col = find_column(df, r'date|month|year|time')
    date_range = "N/A"
    if date_col and date_col in df.columns:
        try:
            min_dt = pd.to_datetime(df[date_col]).min()
            max_dt = pd.to_datetime(df[date_col]).max()
            if min_dt.year == max_dt.year:
                date_range = f"{min_dt.strftime('%d %b')} - {max_dt.strftime('%d %b %Y')}"
            else:
                date_range = f"{min_dt.strftime('%d %b %Y')} - {max_dt.strftime('%d %b %Y')}"
        except: pass
        
    stat_table = Table([
        [f"Rows: {len(df)}", f"Columns: {len(df.columns)}", f"Date Range: {date_range}"]
    ], colWidths=[doc.width/3]*3)
    stat_table.setStyle(TableStyle([
        ('FONT', (0,0), (-1,-1), 'Helvetica-Bold', 10),
        ('TEXTCOLOR', (0,0), (-1,-1), INK),
        ('BACKGROUND', (0,0), (-1,-1), LIGHT_ROW_FILL),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 8),
        ('RIGHTPADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(stat_table)
    story.append(Spacer(1, 20))
    
    section_header("Executive Snapshot")
    
    # Quality Score Visual
    q_score = dataset_info.get('quality_score', 0)
    q_color = POSITIVE if q_score >= 85 else colors.HexColor('#F59E0B') if q_score >= 60 else NEGATIVE
    breakdown = dataset_info.get('quality_breakdown', {})
    if isinstance(breakdown, str):
        try: breakdown = json.loads(breakdown)
        except: breakdown = {}
        
    mini_bars = []
    labels = []
    for k in ["completeness", "uniqueness", "type_consistency", "validity"]:
        val = breakdown.get(k, 0)
        c = POSITIVE if val >= 85 else colors.HexColor('#F59E0B') if val >= 60 else NEGATIVE
        labels.append(f"{k.replace('type_', '').capitalize()}: {val:.1f}%")
        width = max((val/100)*1.5*inch, 0.05*inch)
        mini_bars.append(Table([[""]], colWidths=[width], rowHeights=[10], style=TableStyle([('BACKGROUND', (0,0), (0,0), c)])))
        
    story.append(Paragraph(f"<b>Data Quality Score:</b> <font color='{q_color.hexval()}'>{q_score:.1f}/100</font>", body_style))
    story.append(Spacer(1, 4))
    
    b_table = Table([labels, mini_bars], colWidths=[1.5*inch]*4)
    b_table.setStyle(TableStyle([
        ('FONT', (0,0), (-1,-1), 'Helvetica', 8),
        ('TEXTCOLOR', (0,0), (-1,-1), MUTED_GRAY),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 2),
        ('TOPPADDING', (0,0), (-1,-1), 2),
    ]))
    story.append(b_table)
    story.append(Spacer(1, 20))
    
    story.append(Paragraph("<b>Report Contents</b>", body_style))
    contents = [
        "• KPI Dashboard",
        "• Revenue / Metric Chart",
        "• Monthly Values",
        "• Segment Breakdown",
        "• Numeric Columns Summary",
        "• Statistical Outliers",
        "• Regression Models",
        "• Forecast"
    ]
    for c in contents:
        story.append(Paragraph(c, body_style))
        
    story.append(PageBreak())
    
    # ================= PAGE 2 =================
    section_header("KPI Dashboard")
    kpi_results = compute_kpis(df)
    kpis = kpi_results.get("kpis", [])
    
    if kpis:
        kpi_cells = []
        for k in kpis:
            name = k.get('name', '')
            value = k.get('value', 0)
            prev = k.get('previous_value', 0)
            trend_pct = k.get('trend', 0)
            delta = value - prev
            fmt_val = format_number(value)
            
            t_color = '#16A34A' if delta > 0 else '#DC2626' if delta < 0 else '#64748B'
            t_char = "▲" if delta > 0 else "▼" if delta < 0 else "—"
            trend_str_val = f"{trend_pct:+.1f}%" if isinstance(trend_pct, (int, float)) else f"{trend_pct}%"
            if delta == 0: trend_str_val = "0.0%"
            t_str = f"<font color='{t_color}'>{t_char} {trend_str_val}</font>"
            
            card_table = Table([
                [Paragraph(name, kpi_name_style)],
                [Paragraph(fmt_val, kpi_val_style)],
                [Paragraph(t_str, kpi_trend_style)],
                [Paragraph(f"Source: {k.get('column','')}", kpi_source_style)]
            ], colWidths=[(doc.width/2)-24])
            card_table.setStyle(TableStyle([
                ('TOPPADDING', (0,0), (0,0), 6),
                ('BOTTOMPADDING', (0,-1), (0,-1), 6),
                ('LEFTPADDING', (0,0), (-1,-1), 0),
                ('RIGHTPADDING', (0,0), (-1,-1), 0),
                ('BOTTOMPADDING', (0,0), (-1,-2), 2),
                ('TOPPADDING', (0,1), (-1,-1), 2),
            ]))
            kpi_cells.append(card_table)
            
        # Reshape to grid
        if len(kpi_cells) == 3:
            for cell in kpi_cells:
                cell._colWidths = [(doc.width/3)-24]
            grid_data = [[kpi_cells[0], kpi_cells[1], kpi_cells[2]]]
            kpi_grid = Table(grid_data, colWidths=[doc.width/3]*3)
        else:
            grid_data = []
            for i in range(0, len(kpi_cells), 2):
                row = [kpi_cells[i]]
                if i+1 < len(kpi_cells): row.append(kpi_cells[i+1])
                else: row.append("")
                grid_data.append(row)
                
            kpi_grid = Table(grid_data, colWidths=[doc.width/2]*2)
        kpi_grid.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('BOX', (0,0), (-1,-1), 0.5, LIGHT_ROW_FILL),
            ('INNERGRID', (0,0), (-1,-1), 0.5, LIGHT_ROW_FILL),
            ('PADDING', (0,0), (-1,-1), 12),
        ]))
        story.append(kpi_grid)
        story.append(Spacer(1, 15))
        
        # Deterministic paragraph
        rev_kpi = next((k for k in kpis if k.get('name') == 'Total Revenue'), None)
        if rev_kpi and date_col:
            rev_val = rev_kpi.get('value', 0)
            rev_trend = rev_kpi.get('trend', 0)
            rev_delta = rev_val - rev_kpi.get('previous_value', 0)
            inc_dec = "increase" if rev_delta >= 0 else "decrease"
            
            # Find largest segment in latest month
            df_temp = df.copy()
            df_temp[date_col] = pd.to_datetime(df_temp[date_col], errors='coerce')
            latest_month = df_temp[date_col].max()
            if pd.notna(latest_month):
                df_latest = df_temp[df_temp[date_col].dt.to_period('M') == latest_month.to_period('M')]
                cat_cols = df.select_dtypes(exclude=[np.number, 'datetime64']).columns
                top_seg = None
                top_share = 0
                for c in cat_cols:
                    if 'id' in c.lower() or df[c].nunique() > 20: continue
                    grp = df_latest.groupby(c)[rev_kpi['column']].sum()
                    if len(grp) > 0:
                        grp_pct = grp / grp.sum() * 100
                        best = grp_pct.idxmax()
                        if grp_pct[best] > top_share:
                            top_share = grp_pct[best]
                            top_seg = f"{c} ({best})"
                
                seg_text = f" The largest contributing segment was {top_seg} ({top_share:.1f}%)." if top_seg else ""
                
                para = f"Total revenue for the latest period was {format_number(rev_val)}, a {abs(rev_trend)}% {inc_dec} vs the prior period.{seg_text}"
                story.append(Paragraph(para, body_style))
                
    story.append(PageBreak())
    
    # ================= PAGE 3 =================
    section_header("Revenue / Metric Chart")
    
    chart_data = kpi_results.get("chart_data", [])
    rev_col = find_column(df, r'revenue|sales|amount')
    
    if date_col and rev_col and chart_data:
        plt.figure(figsize=(8, 4.5), dpi=200)
        ax = plt.gca()
        
        hist_data = [d for d in chart_data if d.get("value") is not None]
        fcst_data = [d for d in chart_data if d.get("forecast") is not None and d.get("value") is None]
        
        if hist_data and fcst_data:
            last_hist = hist_data[-1].copy()
            last_hist["forecast"] = last_hist["value"]
            fcst_data.insert(0, last_hist)
            
        fcst_bounds = None
        if fcst_data and len(fcst_data) > 1:
            f_res = forecast_series(df, rev_col, periods=len(fcst_data)-1)
            if f_res.get("available"):
                fcst_bounds = f_res.get("forecast")
                
        x_hist = [d["name"] for d in hist_data]
        y_hist = [d["value"] for d in hist_data]
        
        ax.plot(x_hist, y_hist, color='#2563EB', marker='o', linestyle='-', linewidth=2, label='Actual')
        y_min = min(y_hist)
        ax.fill_between(range(len(x_hist)), y_hist, y_min, alpha=0.05, color='#2563EB')
        
        if hist_data:
            ax.annotate(format_number(y_hist[-1]), (len(x_hist)-1, y_hist[-1]), textcoords="offset points", xytext=(0,10), ha='center', fontsize=8)
            
        if fcst_data:
            x_fcst = [d["name"] for d in fcst_data]
            y_fcst = [d["forecast"] for d in fcst_data]
            
            x_idx = range(len(x_hist)-1, len(x_hist)-1 + len(x_fcst))
            ax.plot(x_fcst, y_fcst, color='#2563EB', linestyle='--', linewidth=2, label='Forecast')
            
            if fcst_bounds:
                y_lower = [y_fcst[0]] + [b["lower"] for b in fcst_bounds]
                y_upper = [y_fcst[0]] + [b["upper"] for b in fcst_bounds]
                ax.fill_between(x_idx, y_lower, y_upper, alpha=0.12, color='#2563EB')
                
            ax.annotate(format_number(y_fcst[-1]), (x_idx[-1], y_fcst[-1]), textcoords="offset points", xytext=(0,10), ha='center', fontsize=8)

        ax.yaxis.set_major_formatter(FuncFormatter(matplotlib_formatter))
        ax.grid(axis='y', linestyle='--', alpha=0.3)
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
        ax.spines['left'].set_color('#E2E8F0')
        ax.spines['bottom'].set_color('#E2E8F0')
        ax.margins(y=0.12)
        ax.set_ylim(bottom=0)
        plt.xticks(rotation=45, ha='right', fontsize=8)
        plt.yticks(fontsize=8)
        ax.legend(loc='lower left', bbox_to_anchor=(0, 1.02), ncol=2, frameon=False, fontsize=8)
        
        plt.tight_layout()
        img_buffer = io.BytesIO()
        plt.savefig(img_buffer, format='png', bbox_inches='tight')
        plt.close()
        img_buffer.seek(0)
        story.append(Image(img_buffer, width=doc.width, height=doc.width*0.56)) # 16:9 ratio
        
        story.append(Spacer(1, 20))
        
        # Monthly Table
        section_header("Monthly Values")
        table_data = [["Period", "Value", "MoM %", "Type"]]
        
        prev_val = None
        for d in chart_data:
            val = d.get("value")
            fcst = d.get("forecast")
            v = val if val is not None else fcst
            typ = "Actual" if val is not None else "Forecast"
            
            mom = "—"
            if prev_val is not None and prev_val > 0:
                pct = ((v - prev_val) / prev_val) * 100
                c = '#16A34A' if pct > 0 else '#DC2626' if pct < 0 else '#64748B'
                mom = Paragraph(f"<font color='{c}'>{pct:+.1f}%</font>", ParagraphStyle('mom', fontName='Helvetica', fontSize=9))
            
            p_style = ParagraphStyle('italic', fontName='Helvetica-Oblique', fontSize=9, textColor=MUTED_GRAY) if typ == "Forecast" else body_style
            
            table_data.append([
                Paragraph(d["name"], p_style),
                Paragraph(format_number(v), p_style),
                mom,
                Paragraph(typ, p_style)
            ])
            prev_val = v
            
        t = Table(table_data, colWidths=[2*inch, 1.5*inch, 1.5*inch, 1.5*inch], repeatRows=1)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), TABLE_HEADER_BG),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONT', (0,0), (-1,0), 'Helvetica-Bold', 9),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('GRID', (0,0), (-1,-1), 0.5, LIGHT_ROW_FILL),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, LIGHT_ROW_FILL])
        ]))
        story.append(KeepTogether([t]))
        
        # Forecast bounds table if available
        if fcst_bounds:
            story.append(Spacer(1, 20))
            section_header("Forecast")
            f_data = [["Period", "Expected", "Lower Bound", "Upper Bound"]]
            for b in fcst_bounds:
                f_data.append([b["date"], format_number(b["forecast"]), format_number(b["lower"]), format_number(b["upper"])])
            ft = Table(f_data, colWidths=[2*inch, 1.5*inch, 1.5*inch, 1.5*inch], repeatRows=1)
            ft.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), TABLE_HEADER_BG),
                ('TEXTCOLOR', (0,0), (-1,0), colors.white),
                ('FONT', (0,0), (-1,-1), 'Helvetica', 9),
                ('FONT', (0,0), (-1,0), 'Helvetica-Bold', 9),
                ('GRID', (0,0), (-1,-1), 0.5, LIGHT_ROW_FILL),
                ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, LIGHT_ROW_FILL])
            ]))
            story.append(KeepTogether([ft, Spacer(1,4), Paragraph("Method: Linear trend projection", caption_style)]))
    else:
        story.append(Paragraph("No time dimension available for charting.", body_style))
        
    story.append(Spacer(1, 20))
    
    # ================= SEGMENT BREAKDOWN =================
    if date_col and rev_col:
        df_temp = df.copy()
        df_temp[date_col] = pd.to_datetime(df_temp[date_col], errors='coerce')
        latest_month = df_temp[date_col].max()
        if pd.notna(latest_month):
            df_latest = df_temp[df_temp[date_col].dt.to_period('M') == latest_month.to_period('M')]
            cat_cols = df.select_dtypes(exclude=[np.number, 'datetime64']).columns
            
            dims = []
            for c in cat_cols:
                if 'id' in c.lower() or df[c].nunique() > 50 or df[c].nunique() < 2: continue
                grp = df_latest.groupby(c)[rev_col].sum().sort_values(ascending=False).head(5)
                if len(grp) > 0: dims.append((c, grp))
                if len(dims) == 3: break
                
            if dims:
                section_header("Segment Breakdown (Latest Month)")
                for c, grp in dims:
                    tot = grp.sum()
                    if tot == 0: continue
                    s_data = [[c, "Value", "Share %"]]
                    for idx, val in grp.items():
                        s_data.append([str(idx), format_number(val), f"{(val/tot*100):.1f}%"])
                    st = Table(s_data, colWidths=[3*inch, 1.5*inch, 1.5*inch], repeatRows=1)
                    st.setStyle(TableStyle([
                        ('BACKGROUND', (0,0), (-1,0), TABLE_HEADER_BG),
                        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
                        ('FONT', (0,0), (-1,-1), 'Helvetica', 9),
                        ('FONT', (0,0), (-1,0), 'Helvetica-Bold', 9),
                        ('GRID', (0,0), (-1,-1), 0.5, LIGHT_ROW_FILL),
                        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, LIGHT_ROW_FILL])
                    ]))
                    story.append(KeepTogether([st]))
                    story.append(Spacer(1, 15))

    # ================= NUMERIC COLUMNS =================
    section_header("Numeric Columns Summary")
    num_cols = df.select_dtypes(include=[np.number]).columns
    if len(num_cols) > 0:
        table_data = [["Column", "Sum", "Mean", "Min", "Max", "Trend"]]
        
        recent_df, prior_df = df, None
        if date_col:
            try:
                periods = df.groupby(pd.to_datetime(df[date_col], errors='coerce').dt.to_period('M'))
                if len(periods) >= 2:
                    sorted_periods = sorted(periods.groups.keys())
                    recent_df = periods.get_group(sorted_periods[-1])
                    prior_df = periods.get_group(sorted_periods[-2])
            except: pass
            
        for col in num_cols[:15]:
            c_sum = format_number(df[col].sum())
            c_mean = format_number(df[col].mean())
            c_min = format_number(df[col].min())
            c_max = format_number(df[col].max())
            
            trend_str = "—"
            if prior_df is not None and not prior_df.empty:
                c_val = recent_df[col].sum()
                p_val = prior_df[col].sum()
                if p_val != 0 and pd.notna(p_val):
                    pct = ((c_val - p_val) / p_val) * 100
                    c = '#16A34A' if pct > 0 else '#DC2626' if pct < 0 else '#64748B'
                    t_char = "▲" if pct > 0 else "▼" if pct < 0 else "—"
                    trend_str = Paragraph(f"<font color='{c}'>{t_char} {pct:+.1f}%</font>", ParagraphStyle('t', fontName='Helvetica', fontSize=9))
                    
            table_data.append([str(col), c_sum, c_mean, c_min, c_max, trend_str])
            
        t2 = Table(table_data, colWidths=[1.8*inch, 1*inch, 1*inch, 1*inch, 1*inch, 1*inch], repeatRows=1)
        t2.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), TABLE_HEADER_BG),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONT', (0,0), (-1,-1), 'Helvetica', 9),
            ('FONT', (0,0), (-1,0), 'Helvetica-Bold', 9),
            ('GRID', (0,0), (-1,-1), 0.5, LIGHT_ROW_FILL),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, LIGHT_ROW_FILL])
        ]))
        story.append(KeepTogether([t2]))
    else:
        story.append(Paragraph("No numeric columns available.", body_style))
        
    story.append(Spacer(1, 20))
    
    # ================= OUTLIERS =================
    section_header("Statistical Outliers")
    outliers = get_outliers(df)
    if outliers:
        o_data = [["Column", "Row Index", "Value", "Expected Range", "Method"]]
        for o in outliers:
            o_data.append([o["column"], o["row"], format_number(o["value"]), o["expected"], o["method"]])
        ot = Table(o_data, colWidths=[1.5*inch, 1*inch, 1*inch, 2*inch, 1.5*inch], repeatRows=1)
        ot.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), TABLE_HEADER_BG),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONT', (0,0), (-1,-1), 'Helvetica', 9),
            ('FONT', (0,0), (-1,0), 'Helvetica-Bold', 9),
            ('GRID', (0,0), (-1,-1), 0.5, LIGHT_ROW_FILL),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, LIGHT_ROW_FILL])
        ]))
        story.append(KeepTogether([ot]))
    else:
        story.append(Paragraph("No statistical outliers detected.", body_style))
        
    story.append(Spacer(1, 20))
    
    # ================= REGRESSION MODELS =================
    models = get_regression_models(dataset_info["id"])
    if models:
        section_header("Regression Models")
        m_data = [["Target", "Features", "R² Test", "Trained Date"]]
        for m in models:
            f_str = ", ".join(m["features"])
            if len(f_str) > 30: f_str = f_str[:27] + "..."
            dt = m["timestamp"].split("T")[0]
            m_data.append([m["target"], f_str, f"{m['r2_test']:.3f}", dt])
            
        mt = Table(m_data, colWidths=[1.5*inch, 3*inch, 1*inch, 1.5*inch], repeatRows=1)
        mt.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), TABLE_HEADER_BG),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONT', (0,0), (-1,-1), 'Helvetica', 9),
            ('FONT', (0,0), (-1,0), 'Helvetica-Bold', 9),
            ('GRID', (0,0), (-1,-1), 0.5, LIGHT_ROW_FILL),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, LIGHT_ROW_FILL])
        ]))
        story.append(KeepTogether([mt]))

    doc.build(story, canvasmaker=lambda *args, **kwargs: FooterCanvas(*args, dataset_name=dataset_info["name"], gen_date=gen_date, **kwargs))
    buffer.seek(0)
    return buffer
